// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: event/v1/event.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event model
type Event struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId              int64                  `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	MessageId           int64                  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	CreatedBy           int64                  `protobuf:"varint,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Title               string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description         string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	EventDate           int64                  `protobuf:"varint,7,opt,name=event_date,json=eventDate,proto3" json:"event_date,omitempty"` // Unix timestamp
	EndDate             int64                  `protobuf:"varint,8,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // Unix timestamp, optional
	Location            string                 `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	EventType           string                 `protobuf:"bytes,10,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`                                 // meeting, reminder, deadline, appointment
	Status              string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`                                                        // active, cancelled, completed
	DetectionConfidence float32                `protobuf:"fixed32,12,opt,name=detection_confidence,json=detectionConfidence,proto3" json:"detection_confidence,omitempty"` // 0.0-1.0
	AutoDetected        bool                   `protobuf:"varint,13,opt,name=auto_detected,json=autoDetected,proto3" json:"auto_detected,omitempty"`
	CalendarSynced      bool                   `protobuf:"varint,14,opt,name=calendar_synced,json=calendarSynced,proto3" json:"calendar_synced,omitempty"`
	ExternalCalendarId  string                 `protobuf:"bytes,15,opt,name=external_calendar_id,json=externalCalendarId,proto3" json:"external_calendar_id,omitempty"`
	Attendees           []*EventAttendee       `protobuf:"bytes,16,rep,name=attendees,proto3" json:"attendees,omitempty"`
	CreatedAt           int64                  `protobuf:"varint,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           int64                  `protobuf:"varint,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Event) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *Event) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Event) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetEventDate() int64 {
	if x != nil {
		return x.EventDate
	}
	return 0
}

func (x *Event) GetEndDate() int64 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

func (x *Event) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Event) GetDetectionConfidence() float32 {
	if x != nil {
		return x.DetectionConfidence
	}
	return 0
}

func (x *Event) GetAutoDetected() bool {
	if x != nil {
		return x.AutoDetected
	}
	return false
}

func (x *Event) GetCalendarSynced() bool {
	if x != nil {
		return x.CalendarSynced
	}
	return false
}

func (x *Event) GetExternalCalendarId() string {
	if x != nil {
		return x.ExternalCalendarId
	}
	return ""
}

func (x *Event) GetAttendees() []*EventAttendee {
	if x != nil {
		return x.Attendees
	}
	return nil
}

func (x *Event) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Event) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Event attendee model
type EventAttendee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`                        // For display purposes
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                            // pending, accepted, declined, maybe
	ResponseAt    int64                  `protobuf:"varint,6,opt,name=response_at,json=responseAt,proto3" json:"response_at,omitempty"` // Unix timestamp
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventAttendee) Reset() {
	*x = EventAttendee{}
	mi := &file_event_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAttendee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAttendee) ProtoMessage() {}

func (x *EventAttendee) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAttendee.ProtoReflect.Descriptor instead.
func (*EventAttendee) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *EventAttendee) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EventAttendee) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *EventAttendee) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EventAttendee) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *EventAttendee) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EventAttendee) GetResponseAt() int64 {
	if x != nil {
		return x.ResponseAt
	}
	return 0
}

func (x *EventAttendee) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// Request/Response messages
type CreateEventRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomId          int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	MessageId       int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // Optional, if creating from a message
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	EventDate       int64                  `protobuf:"varint,5,opt,name=event_date,json=eventDate,proto3" json:"event_date,omitempty"` // Unix timestamp
	EndDate         int64                  `protobuf:"varint,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // Unix timestamp, optional
	Location        string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	EventType       string                 `protobuf:"bytes,8,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	AttendeeUserIds []int64                `protobuf:"varint,9,rep,packed,name=attendee_user_ids,json=attendeeUserIds,proto3" json:"attendee_user_ids,omitempty"` // User IDs to invite
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_event_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEventRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *CreateEventRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *CreateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateEventRequest) GetEventDate() int64 {
	if x != nil {
		return x.EventDate
	}
	return 0
}

func (x *CreateEventRequest) GetEndDate() int64 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

func (x *CreateEventRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *CreateEventRequest) GetAttendeeUserIds() []int64 {
	if x != nil {
		return x.AttendeeUserIds
	}
	return nil
}

type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_event_v1_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`          // Optional, filter by room
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // Optional, filter by user
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                         // Optional, filter by status
	StartDate     int64                  `protobuf:"varint,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // Optional, filter events after this date
	EndDate       int64                  `protobuf:"varint,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // Optional, filter events before this date
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_event_v1_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{4}
}

func (x *ListEventsRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ListEventsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListEventsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListEventsRequest) GetStartDate() int64 {
	if x != nil {
		return x.StartDate
	}
	return 0
}

func (x *ListEventsRequest) GetEndDate() int64 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

func (x *ListEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListEventsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_event_v1_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{5}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListEventsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	EventDate     int64                  `protobuf:"varint,4,opt,name=event_date,json=eventDate,proto3" json:"event_date,omitempty"`
	EndDate       int64                  `protobuf:"varint,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	EventType     string                 `protobuf:"bytes,7,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_event_v1_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEventRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateEventRequest) GetEventDate() int64 {
	if x != nil {
		return x.EventDate
	}
	return 0
}

func (x *UpdateEventRequest) GetEndDate() int64 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

func (x *UpdateEventRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *UpdateEventRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_event_v1_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteEventRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_event_v1_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RsvpEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // accepted, declined, maybe
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RsvpEventRequest) Reset() {
	*x = RsvpEventRequest{}
	mi := &file_event_v1_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RsvpEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsvpEventRequest) ProtoMessage() {}

func (x *RsvpEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsvpEventRequest.ProtoReflect.Descriptor instead.
func (*RsvpEventRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{9}
}

func (x *RsvpEventRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *RsvpEventRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RsvpEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Attendee      *EventAttendee         `protobuf:"bytes,2,opt,name=attendee,proto3" json:"attendee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RsvpEventResponse) Reset() {
	*x = RsvpEventResponse{}
	mi := &file_event_v1_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RsvpEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsvpEventResponse) ProtoMessage() {}

func (x *RsvpEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsvpEventResponse.ProtoReflect.Descriptor instead.
func (*RsvpEventResponse) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{10}
}

func (x *RsvpEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RsvpEventResponse) GetAttendee() *EventAttendee {
	if x != nil {
		return x.Attendee
	}
	return nil
}

// Event detection from messages
type DetectEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	RoomId        int64                  `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // Optional, if detecting from existing message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectEventsRequest) Reset() {
	*x = DetectEventsRequest{}
	mi := &file_event_v1_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectEventsRequest) ProtoMessage() {}

func (x *DetectEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectEventsRequest.ProtoReflect.Descriptor instead.
func (*DetectEventsRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{11}
}

func (x *DetectEventsRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DetectEventsRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *DetectEventsRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type DetectEventsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DetectedEvents []*DetectedEvent       `protobuf:"bytes,1,rep,name=detected_events,json=detectedEvents,proto3" json:"detected_events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DetectEventsResponse) Reset() {
	*x = DetectEventsResponse{}
	mi := &file_event_v1_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectEventsResponse) ProtoMessage() {}

func (x *DetectEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectEventsResponse.ProtoReflect.Descriptor instead.
func (*DetectEventsResponse) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{12}
}

func (x *DetectEventsResponse) GetDetectedEvents() []*DetectedEvent {
	if x != nil {
		return x.DetectedEvents
	}
	return nil
}

type DetectedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	EventDate     int64                  `protobuf:"varint,3,opt,name=event_date,json=eventDate,proto3" json:"event_date,omitempty"`
	EndDate       int64                  `protobuf:"varint,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	EventType     string                 `protobuf:"bytes,6,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Confidence    float32                `protobuf:"fixed32,7,opt,name=confidence,proto3" json:"confidence,omitempty"`                          // 0.0-1.0
	ExtractedText string                 `protobuf:"bytes,8,opt,name=extracted_text,json=extractedText,proto3" json:"extracted_text,omitempty"` // The text that triggered the detection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectedEvent) Reset() {
	*x = DetectedEvent{}
	mi := &file_event_v1_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectedEvent) ProtoMessage() {}

func (x *DetectedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectedEvent.ProtoReflect.Descriptor instead.
func (*DetectedEvent) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{13}
}

func (x *DetectedEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DetectedEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DetectedEvent) GetEventDate() int64 {
	if x != nil {
		return x.EventDate
	}
	return 0
}

func (x *DetectedEvent) GetEndDate() int64 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

func (x *DetectedEvent) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *DetectedEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *DetectedEvent) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DetectedEvent) GetExtractedText() string {
	if x != nil {
		return x.ExtractedText
	}
	return ""
}

// Calendar sync
type SyncToCalendarRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventId          int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	CalendarProvider string                 `protobuf:"bytes,2,opt,name=calendar_provider,json=calendarProvider,proto3" json:"calendar_provider,omitempty"` // google, outlook, ical
	CalendarId       string                 `protobuf:"bytes,3,opt,name=calendar_id,json=calendarId,proto3" json:"calendar_id,omitempty"`                   // Optional, specific calendar ID
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncToCalendarRequest) Reset() {
	*x = SyncToCalendarRequest{}
	mi := &file_event_v1_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncToCalendarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncToCalendarRequest) ProtoMessage() {}

func (x *SyncToCalendarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncToCalendarRequest.ProtoReflect.Descriptor instead.
func (*SyncToCalendarRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{14}
}

func (x *SyncToCalendarRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *SyncToCalendarRequest) GetCalendarProvider() string {
	if x != nil {
		return x.CalendarProvider
	}
	return ""
}

func (x *SyncToCalendarRequest) GetCalendarId() string {
	if x != nil {
		return x.CalendarId
	}
	return ""
}

type SyncToCalendarResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ExternalCalendarId string                 `protobuf:"bytes,2,opt,name=external_calendar_id,json=externalCalendarId,proto3" json:"external_calendar_id,omitempty"`
	CalendarUrl        string                 `protobuf:"bytes,3,opt,name=calendar_url,json=calendarUrl,proto3" json:"calendar_url,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SyncToCalendarResponse) Reset() {
	*x = SyncToCalendarResponse{}
	mi := &file_event_v1_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncToCalendarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncToCalendarResponse) ProtoMessage() {}

func (x *SyncToCalendarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncToCalendarResponse.ProtoReflect.Descriptor instead.
func (*SyncToCalendarResponse) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{15}
}

func (x *SyncToCalendarResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncToCalendarResponse) GetExternalCalendarId() string {
	if x != nil {
		return x.ExternalCalendarId
	}
	return ""
}

func (x *SyncToCalendarResponse) GetCalendarUrl() string {
	if x != nil {
		return x.CalendarUrl
	}
	return ""
}

var File_event_v1_event_proto protoreflect.FileDescriptor

const file_event_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x14event/v1/event.proto\x12\fapi.event.v1\x1a\x1cgoogle/api/annotations.proto\"\xdf\x04\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\x03R\x06roomId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\x03R\tcreatedBy\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"event_date\x18\a \x01(\x03R\teventDate\x12\x19\n" +
	"\bend_date\x18\b \x01(\x03R\aendDate\x12\x1a\n" +
	"\blocation\x18\t \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"event_type\x18\n" +
	" \x01(\tR\teventType\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x121\n" +
	"\x14detection_confidence\x18\f \x01(\x02R\x13detectionConfidence\x12#\n" +
	"\rauto_detected\x18\r \x01(\bR\fautoDetected\x12'\n" +
	"\x0fcalendar_synced\x18\x0e \x01(\bR\x0ecalendarSynced\x120\n" +
	"\x14external_calendar_id\x18\x0f \x01(\tR\x12externalCalendarId\x129\n" +
	"\tattendees\x18\x10 \x03(\v2\x1b.api.event.v1.EventAttendeeR\tattendees\x12\x1d\n" +
	"\n" +
	"created_at\x18\x11 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\x03R\tupdatedAt\"\xc7\x01\n" +
	"\rEventAttendee\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\vresponse_at\x18\x06 \x01(\x03R\n" +
	"responseAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"\xa5\x02\n" +
	"\x12CreateEventRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"event_date\x18\x05 \x01(\x03R\teventDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\x03R\aendDate\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"event_type\x18\b \x01(\tR\teventType\x12*\n" +
	"\x11attendee_user_ids\x18\t \x03(\x03R\x0fattendeeUserIds\"!\n" +
	"\x0fGetEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xc5\x01\n" +
	"\x11ListEventsRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\x03R\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\x03R\aendDate\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\a \x01(\x05R\x06offset\"W\n" +
	"\x12ListEventsResponse\x12+\n" +
	"\x06events\x18\x01 \x03(\v2\x13.api.event.v1.EventR\x06events\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xe9\x01\n" +
	"\x12UpdateEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"event_date\x18\x04 \x01(\x03R\teventDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\x03R\aendDate\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"event_type\x18\a \x01(\tR\teventType\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"$\n" +
	"\x12DeleteEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"/\n" +
	"\x13DeleteEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"E\n" +
	"\x10RsvpEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"f\n" +
	"\x11RsvpEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x127\n" +
	"\battendee\x18\x02 \x01(\v2\x1b.api.event.v1.EventAttendeeR\battendee\"a\n" +
	"\x13DetectEventsRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\x03R\x06roomId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId\"\\\n" +
	"\x14DetectEventsResponse\x12D\n" +
	"\x0fdetected_events\x18\x01 \x03(\v2\x1b.api.event.v1.DetectedEventR\x0edetectedEvents\"\x83\x02\n" +
	"\rDetectedEvent\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"event_date\x18\x03 \x01(\x03R\teventDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\x03R\aendDate\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"event_type\x18\x06 \x01(\tR\teventType\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x02R\n" +
	"confidence\x12%\n" +
	"\x0eextracted_text\x18\b \x01(\tR\rextractedText\"\x80\x01\n" +
	"\x15SyncToCalendarRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12+\n" +
	"\x11calendar_provider\x18\x02 \x01(\tR\x10calendarProvider\x12\x1f\n" +
	"\vcalendar_id\x18\x03 \x01(\tR\n" +
	"calendarId\"\x87\x01\n" +
	"\x16SyncToCalendarResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x120\n" +
	"\x14external_calendar_id\x18\x02 \x01(\tR\x12externalCalendarId\x12!\n" +
	"\fcalendar_url\x18\x03 \x01(\tR\vcalendarUrl2\x87\a\n" +
	"\fEventService\x12_\n" +
	"\vCreateEvent\x12 .api.event.v1.CreateEventRequest\x1a\x13.api.event.v1.Event\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/events\x12[\n" +
	"\bGetEvent\x12\x1d.api.event.v1.GetEventRequest\x1a\x13.api.event.v1.Event\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/events/{id}\x12g\n" +
	"\n" +
	"ListEvents\x12\x1f.api.event.v1.ListEventsRequest\x1a .api.event.v1.ListEventsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/events\x12d\n" +
	"\vUpdateEvent\x12 .api.event.v1.UpdateEventRequest\x1a\x13.api.event.v1.Event\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/api/v1/events/{id}\x12o\n" +
	"\vDeleteEvent\x12 .api.event.v1.DeleteEventRequest\x1a!.api.event.v1.DeleteEventResponse\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/api/v1/events/{id}\x12w\n" +
	"\tRsvpEvent\x12\x1e.api.event.v1.RsvpEventRequest\x1a\x1f.api.event.v1.RsvpEventResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/v1/events/{event_id}/rsvp\x12w\n" +
	"\fDetectEvents\x12!.api.event.v1.DetectEventsRequest\x1a\".api.event.v1.DetectEventsResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/events/detect\x12\x86\x01\n" +
	"\x0eSyncToCalendar\x12#.api.event.v1.SyncToCalendarRequest\x1a$.api.event.v1.SyncToCalendarResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/v1/events/{event_id}/syncB2Z0github.com/yourusername/chat-app/api/event/v1;v1b\x06proto3"

var (
	file_event_v1_event_proto_rawDescOnce sync.Once
	file_event_v1_event_proto_rawDescData []byte
)

func file_event_v1_event_proto_rawDescGZIP() []byte {
	file_event_v1_event_proto_rawDescOnce.Do(func() {
		file_event_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_v1_event_proto_rawDesc), len(file_event_v1_event_proto_rawDesc)))
	})
	return file_event_v1_event_proto_rawDescData
}

var file_event_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_event_v1_event_proto_goTypes = []any{
	(*Event)(nil),                  // 0: api.event.v1.Event
	(*EventAttendee)(nil),          // 1: api.event.v1.EventAttendee
	(*CreateEventRequest)(nil),     // 2: api.event.v1.CreateEventRequest
	(*GetEventRequest)(nil),        // 3: api.event.v1.GetEventRequest
	(*ListEventsRequest)(nil),      // 4: api.event.v1.ListEventsRequest
	(*ListEventsResponse)(nil),     // 5: api.event.v1.ListEventsResponse
	(*UpdateEventRequest)(nil),     // 6: api.event.v1.UpdateEventRequest
	(*DeleteEventRequest)(nil),     // 7: api.event.v1.DeleteEventRequest
	(*DeleteEventResponse)(nil),    // 8: api.event.v1.DeleteEventResponse
	(*RsvpEventRequest)(nil),       // 9: api.event.v1.RsvpEventRequest
	(*RsvpEventResponse)(nil),      // 10: api.event.v1.RsvpEventResponse
	(*DetectEventsRequest)(nil),    // 11: api.event.v1.DetectEventsRequest
	(*DetectEventsResponse)(nil),   // 12: api.event.v1.DetectEventsResponse
	(*DetectedEvent)(nil),          // 13: api.event.v1.DetectedEvent
	(*SyncToCalendarRequest)(nil),  // 14: api.event.v1.SyncToCalendarRequest
	(*SyncToCalendarResponse)(nil), // 15: api.event.v1.SyncToCalendarResponse
}
var file_event_v1_event_proto_depIdxs = []int32{
	1,  // 0: api.event.v1.Event.attendees:type_name -> api.event.v1.EventAttendee
	0,  // 1: api.event.v1.ListEventsResponse.events:type_name -> api.event.v1.Event
	1,  // 2: api.event.v1.RsvpEventResponse.attendee:type_name -> api.event.v1.EventAttendee
	13, // 3: api.event.v1.DetectEventsResponse.detected_events:type_name -> api.event.v1.DetectedEvent
	2,  // 4: api.event.v1.EventService.CreateEvent:input_type -> api.event.v1.CreateEventRequest
	3,  // 5: api.event.v1.EventService.GetEvent:input_type -> api.event.v1.GetEventRequest
	4,  // 6: api.event.v1.EventService.ListEvents:input_type -> api.event.v1.ListEventsRequest
	6,  // 7: api.event.v1.EventService.UpdateEvent:input_type -> api.event.v1.UpdateEventRequest
	7,  // 8: api.event.v1.EventService.DeleteEvent:input_type -> api.event.v1.DeleteEventRequest
	9,  // 9: api.event.v1.EventService.RsvpEvent:input_type -> api.event.v1.RsvpEventRequest
	11, // 10: api.event.v1.EventService.DetectEvents:input_type -> api.event.v1.DetectEventsRequest
	14, // 11: api.event.v1.EventService.SyncToCalendar:input_type -> api.event.v1.SyncToCalendarRequest
	0,  // 12: api.event.v1.EventService.CreateEvent:output_type -> api.event.v1.Event
	0,  // 13: api.event.v1.EventService.GetEvent:output_type -> api.event.v1.Event
	5,  // 14: api.event.v1.EventService.ListEvents:output_type -> api.event.v1.ListEventsResponse
	0,  // 15: api.event.v1.EventService.UpdateEvent:output_type -> api.event.v1.Event
	8,  // 16: api.event.v1.EventService.DeleteEvent:output_type -> api.event.v1.DeleteEventResponse
	10, // 17: api.event.v1.EventService.RsvpEvent:output_type -> api.event.v1.RsvpEventResponse
	12, // 18: api.event.v1.EventService.DetectEvents:output_type -> api.event.v1.DetectEventsResponse
	15, // 19: api.event.v1.EventService.SyncToCalendar:output_type -> api.event.v1.SyncToCalendarResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_event_v1_event_proto_init() }
func file_event_v1_event_proto_init() {
	if File_event_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_v1_event_proto_rawDesc), len(file_event_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_v1_event_proto_goTypes,
		DependencyIndexes: file_event_v1_event_proto_depIdxs,
		MessageInfos:      file_event_v1_event_proto_msgTypes,
	}.Build()
	File_event_v1_event_proto = out.File
	file_event_v1_event_proto_goTypes = nil
	file_event_v1_event_proto_depIdxs = nil
}
