// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.29.3
// source: event/v1/event.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationEventServiceCreateEvent = "/api.event.v1.EventService/CreateEvent"
const OperationEventServiceDeleteEvent = "/api.event.v1.EventService/DeleteEvent"
const OperationEventServiceDetectEvents = "/api.event.v1.EventService/DetectEvents"
const OperationEventServiceGetEvent = "/api.event.v1.EventService/GetEvent"
const OperationEventServiceListEvents = "/api.event.v1.EventService/ListEvents"
const OperationEventServiceRsvpEvent = "/api.event.v1.EventService/RsvpEvent"
const OperationEventServiceSyncToCalendar = "/api.event.v1.EventService/SyncToCalendar"
const OperationEventServiceUpdateEvent = "/api.event.v1.EventService/UpdateEvent"

type EventServiceHTTPServer interface {
	// CreateEvent Create a new event
	CreateEvent(context.Context, *CreateEventRequest) (*Event, error)
	// DeleteEvent Delete an event
	DeleteEvent(context.Context, *DeleteEventRequest) (*DeleteEventResponse, error)
	// DetectEvents Detect events from message text
	DetectEvents(context.Context, *DetectEventsRequest) (*DetectEventsResponse, error)
	// GetEvent Get event by ID
	GetEvent(context.Context, *GetEventRequest) (*Event, error)
	// ListEvents List events for a room or user
	ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error)
	// RsvpEvent RSVP to an event
	RsvpEvent(context.Context, *RsvpEventRequest) (*RsvpEventResponse, error)
	// SyncToCalendar Sync event to external calendar
	SyncToCalendar(context.Context, *SyncToCalendarRequest) (*SyncToCalendarResponse, error)
	// UpdateEvent Update an event
	UpdateEvent(context.Context, *UpdateEventRequest) (*Event, error)
}

func RegisterEventServiceHTTPServer(s *http.Server, srv EventServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/events", _EventService_CreateEvent0_HTTP_Handler(srv))
	r.GET("/api/v1/events/{id}", _EventService_GetEvent0_HTTP_Handler(srv))
	r.GET("/api/v1/events", _EventService_ListEvents0_HTTP_Handler(srv))
	r.PUT("/api/v1/events/{id}", _EventService_UpdateEvent0_HTTP_Handler(srv))
	r.DELETE("/api/v1/events/{id}", _EventService_DeleteEvent0_HTTP_Handler(srv))
	r.POST("/api/v1/events/{event_id}/rsvp", _EventService_RsvpEvent0_HTTP_Handler(srv))
	r.POST("/api/v1/events/detect", _EventService_DetectEvents0_HTTP_Handler(srv))
	r.POST("/api/v1/events/{event_id}/sync", _EventService_SyncToCalendar0_HTTP_Handler(srv))
}

func _EventService_CreateEvent0_HTTP_Handler(srv EventServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateEventRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventServiceCreateEvent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateEvent(ctx, req.(*CreateEventRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Event)
		return ctx.Result(200, reply)
	}
}

func _EventService_GetEvent0_HTTP_Handler(srv EventServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetEventRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventServiceGetEvent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetEvent(ctx, req.(*GetEventRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Event)
		return ctx.Result(200, reply)
	}
}

func _EventService_ListEvents0_HTTP_Handler(srv EventServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListEventsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventServiceListEvents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEvents(ctx, req.(*ListEventsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListEventsResponse)
		return ctx.Result(200, reply)
	}
}

func _EventService_UpdateEvent0_HTTP_Handler(srv EventServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateEventRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventServiceUpdateEvent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateEvent(ctx, req.(*UpdateEventRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Event)
		return ctx.Result(200, reply)
	}
}

func _EventService_DeleteEvent0_HTTP_Handler(srv EventServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteEventRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventServiceDeleteEvent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteEvent(ctx, req.(*DeleteEventRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteEventResponse)
		return ctx.Result(200, reply)
	}
}

func _EventService_RsvpEvent0_HTTP_Handler(srv EventServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RsvpEventRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventServiceRsvpEvent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RsvpEvent(ctx, req.(*RsvpEventRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RsvpEventResponse)
		return ctx.Result(200, reply)
	}
}

func _EventService_DetectEvents0_HTTP_Handler(srv EventServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DetectEventsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventServiceDetectEvents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DetectEvents(ctx, req.(*DetectEventsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DetectEventsResponse)
		return ctx.Result(200, reply)
	}
}

func _EventService_SyncToCalendar0_HTTP_Handler(srv EventServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SyncToCalendarRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEventServiceSyncToCalendar)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SyncToCalendar(ctx, req.(*SyncToCalendarRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SyncToCalendarResponse)
		return ctx.Result(200, reply)
	}
}

type EventServiceHTTPClient interface {
	CreateEvent(ctx context.Context, req *CreateEventRequest, opts ...http.CallOption) (rsp *Event, err error)
	DeleteEvent(ctx context.Context, req *DeleteEventRequest, opts ...http.CallOption) (rsp *DeleteEventResponse, err error)
	DetectEvents(ctx context.Context, req *DetectEventsRequest, opts ...http.CallOption) (rsp *DetectEventsResponse, err error)
	GetEvent(ctx context.Context, req *GetEventRequest, opts ...http.CallOption) (rsp *Event, err error)
	ListEvents(ctx context.Context, req *ListEventsRequest, opts ...http.CallOption) (rsp *ListEventsResponse, err error)
	RsvpEvent(ctx context.Context, req *RsvpEventRequest, opts ...http.CallOption) (rsp *RsvpEventResponse, err error)
	SyncToCalendar(ctx context.Context, req *SyncToCalendarRequest, opts ...http.CallOption) (rsp *SyncToCalendarResponse, err error)
	UpdateEvent(ctx context.Context, req *UpdateEventRequest, opts ...http.CallOption) (rsp *Event, err error)
}

type EventServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewEventServiceHTTPClient(client *http.Client) EventServiceHTTPClient {
	return &EventServiceHTTPClientImpl{client}
}

func (c *EventServiceHTTPClientImpl) CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...http.CallOption) (*Event, error) {
	var out Event
	pattern := "/api/v1/events"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEventServiceCreateEvent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventServiceHTTPClientImpl) DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...http.CallOption) (*DeleteEventResponse, error) {
	var out DeleteEventResponse
	pattern := "/api/v1/events/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEventServiceDeleteEvent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventServiceHTTPClientImpl) DetectEvents(ctx context.Context, in *DetectEventsRequest, opts ...http.CallOption) (*DetectEventsResponse, error) {
	var out DetectEventsResponse
	pattern := "/api/v1/events/detect"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEventServiceDetectEvents))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventServiceHTTPClientImpl) GetEvent(ctx context.Context, in *GetEventRequest, opts ...http.CallOption) (*Event, error) {
	var out Event
	pattern := "/api/v1/events/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEventServiceGetEvent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventServiceHTTPClientImpl) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...http.CallOption) (*ListEventsResponse, error) {
	var out ListEventsResponse
	pattern := "/api/v1/events"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationEventServiceListEvents))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventServiceHTTPClientImpl) RsvpEvent(ctx context.Context, in *RsvpEventRequest, opts ...http.CallOption) (*RsvpEventResponse, error) {
	var out RsvpEventResponse
	pattern := "/api/v1/events/{event_id}/rsvp"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEventServiceRsvpEvent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventServiceHTTPClientImpl) SyncToCalendar(ctx context.Context, in *SyncToCalendarRequest, opts ...http.CallOption) (*SyncToCalendarResponse, error) {
	var out SyncToCalendarResponse
	pattern := "/api/v1/events/{event_id}/sync"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEventServiceSyncToCalendar))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *EventServiceHTTPClientImpl) UpdateEvent(ctx context.Context, in *UpdateEventRequest, opts ...http.CallOption) (*Event, error) {
	var out Event
	pattern := "/api/v1/events/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEventServiceUpdateEvent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
